/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transitoffice;

import receive.PackageQueueManager;
import sender_information.Packages;

import java.awt.Font;
import java.util.PriorityQueue;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author HAI YEN
 */
public class ProcessFrame extends javax.swing.JFrame {
    public static PackageQueueManager packageQueueManager;

    /**
     * Creates new form TransitFrame
     */
    public ProcessFrame(PackageQueueManager packageQueueManager) {
        this.packageQueueManager = packageQueueManager;
        initComponents();
        displayInfor();
        this.setLocationRelativeTo(null);
        // Đặt kiểu căn giữa cho ô trong JTable
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.setDefaultRenderer(Object.class, centerRenderer);
        settingTableHeading();
        this.setVisible(true);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        title = new javax.swing.JLabel();
        inforTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        transitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THÔNG TIN ĐƠN HÀNG BƯU CỤC HÀ NỘI");

        title.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        title.setText("THÔNG TIN CÁC ĐƠN HÀNG TẠI BƯU CỤC HÀ NỘI");

        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Mã đơn", "Người gửi", "Người nhận", "Địa chỉ nhận", "Tên hàng hoá", "Số điện thoại", "Dịch vụ"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setSelectionBackground(new java.awt.Color(51, 102, 255));
        table.getTableHeader().setReorderingAllowed(false);
        inforTable.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setPreferredWidth(110);
            table.getColumnModel().getColumn(2).setPreferredWidth(110);
            table.getColumnModel().getColumn(3).setPreferredWidth(320);
        }

        transitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        transitButton.setText("Vận chuyển các đơn hàng về bưu cục quận");
        transitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(title)
                                .addContainerGap(340, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(inforTable)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(transitButton)
                                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(inforTable, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(transitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void transitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
        TransitFrame transitFrame = new TransitFrame(packageQueueManager.getPackageQueue());
    }

    public void displayInfor(){
        // Tạo một bản sao của PriorityQueue để duyệt qua
        PriorityQueue<Packages> tempQueue = new PriorityQueue<>(packageQueueManager.getPackageQueue());
        // Lấy dữ liệu từ PriorityQueue và hiển thị trên bảng
        while (!tempQueue.isEmpty()) {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            Packages pack = tempQueue.poll();
            model.addRow(new Object[]{pack.getId(), pack.getSender(), pack.getReceiver(), pack.getAddress(), pack.getGoods(), pack.getPhonenumber(), pack.getService()});
        }
    }

    private void settingTableHeading(){
        // Lấy JTableHeader của bảng
        JTableHeader header = table.getTableHeader();

        // Tạo một Font mới
        Font headerFont = new Font("Times New Roman", Font.BOLD, 12); // Thay đổi font tại đây

        // Đặt font cho tiêu đề cột
        header.setFont(headerFont);

        // Tạo một TableCellRenderer tùy chỉnh để căn giữa tiêu đề cột
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER); // Căn giữa

        // Đặt renderer cho tất cả các cột trong JTableHeader
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setHeaderRenderer(centerRenderer);
        }
    }




    // Variables declaration - do not modify
    private javax.swing.JScrollPane inforTable;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    private javax.swing.JButton transitButton;
    // End of variables declaration
}
